// activities
export 'package:mimir/module/activity/entity/detail.dart';
export 'package:mimir/module/activity/entity/list.dart';
export 'package:mimir/module/activity/entity/score.dart';
// application
export 'package:mimir/module/application/entity/application.dart';
export 'package:mimir/module/application/entity/message.dart';
// exam_arr
export 'package:mimir/module/exam_arr/entity/exam.dart';
// exam_result
export 'package:mimir/module/exam_result/entity/result.dart';
// oa_announce
export 'package:mimir/module/oa_announce/entity/announce.dart';
export 'package:mimir/module/oa_announce/entity/attachment.dart';
// timetable
export 'package:mimir/module/timetable/entity/entity.dart';
// yellow_pages
export 'package:mimir/module/yellow_pages/entity/contact.dart';
